import glob
import os
from shutil import rmtree

from astra_web._aux import filter_has_prefix
from astra_web.file import find_symlinks, read_json, read_txt, write_json, write_txt
from astra_web.host_localizer import HostLocalizer
from astra_web.status import DispatchStatus
from astra_web.uuid import get_uuid

from .schemas.io import (
    GeneratorData,
    GeneratorMeta,
    GeneratorDispatchOutput,
    GeneratorInput,
    GeneratorOutput,
)
from .schemas.particles import Particles


async def dispatch_particle_distribution_generation(
    generator_input: GeneratorInput,
    local_localizer: HostLocalizer,
    host_localizer: HostLocalizer,
) -> GeneratorDispatchOutput:
    """Dispatches the generation of a particle distribution based on the provided generator input.
    The generator input is written to disk, and the generation is dispatched to the appropriate host.
    """
    # local
    _write_generator_files(generator_input, local_localizer)
    # 'remote'
    response = await host_localizer.dispatch_generation(
        generator_input,
    )
    return GeneratorDispatchOutput(
        gen_id=generator_input.id,
        dispatch_response=response,
    )


def _write_generator_files(
    generator_input: GeneratorInput, localizer: HostLocalizer
) -> None:
    path = localizer.generator_path(generator_input.id)
    os.makedirs(path, exist_ok=True)
    write_json(
        generator_input, localizer.generator_path(generator_input.id, "input.json")
    )
    write_txt(
        generator_input.to_ini(),
        localizer.generator_path(generator_input.id, "generator.in"),
    )


def load_generator_data(
    gen_id: str,
    localizer: HostLocalizer,
    include: list[str] | None = None,
) -> GeneratorData | None:
    """
    Loads the generator output for a given generator ID.
    Returns None if the particle distribution does not exist.


    Parameters:
        include: Optional list of feature paths to include. All others are excluded. If `None`, all features are included.
            Example: `["input.run", "output"]`

    """
    if not os.path.exists(localizer.generator_path(gen_id, "distribution.ini")):
        return None

    input = (
        load_generator_input(gen_id, localizer)
        if filter_has_prefix(include, "input")
        else None
    )

    output = (
        _load_output(gen_id, localizer)
        if filter_has_prefix(include, "output")
        else None
    )

    astra_input = (
        _load_generator_input(gen_id, localizer)
        if filter_has_prefix(include, "astra_input")
        else None
    )

    astra_output = (
        _load_generator_output(gen_id, localizer)
        if filter_has_prefix(include, "astra_output")
        else None
    )

    meta = _load_meta(gen_id, localizer) if filter_has_prefix(include, "meta") else None

    return GeneratorData(
        input=input,
        output=output,
        astra_input=astra_input,
        astra_output=astra_output,
        meta=meta,
    )


def load_generator_input(
    gen_id: str, localizer: HostLocalizer
) -> GeneratorInput | None:
    """
    Loads the generator input for a given generator ID.
    """
    input_path = localizer.generator_path(gen_id, "input.json")
    if os.path.exists(input_path):
        return read_json(GeneratorInput, input_path)
    return None


def _load_output(gen_id: str, localizer: HostLocalizer) -> GeneratorOutput | None:
    return GeneratorOutput(particles=_load_particle_file(gen_id, localizer))


def _load_particle_file(gen_id: str, localizer: HostLocalizer) -> Particles:
    """
    Reads the particle file generated by the ASTRA generator."""
    path = localizer.generator_path(gen_id, "distribution.ini")

    return Particles.read_from_csv(path)


def _load_generator_input(gen_id: str, localizer: HostLocalizer) -> str | None:
    astra_input_path = localizer.generator_path(gen_id, "generator.in")
    if os.path.exists(astra_input_path):
        return read_txt(astra_input_path)
    return None


def _load_generator_output(gen_id: str, localizer: HostLocalizer) -> str | None:
    astra_output_path = localizer.generator_path(gen_id, "generator.out")
    if os.path.exists(astra_output_path):
        return read_txt(astra_output_path)
    return None


def _load_meta(gen_id: str, localizer: HostLocalizer) -> GeneratorMeta | None:
    meta_path = localizer.generator_path(gen_id, "meta.json")
    if os.path.exists(meta_path):
        return read_json(GeneratorMeta, meta_path)
    return None


def list_generator_ids(
    localizer: HostLocalizer,
    state: DispatchStatus | None = None,
) -> list[str]:
    """
    Lists IDs of particle distribution generations.
    """

    ids_all = map(
        lambda p: os.path.basename(p),
        glob.glob(localizer.generator_path("*")),
    )

    if state is None:
        return sorted(ids_all)
    else:
        return sorted(
            id for id in ids_all if get_generation_status(id, localizer) == state
        )


def list_particle_distribution_states(
    localizer: HostLocalizer,
    gen_ids: list[str] | None = None,
) -> list[tuple[str, DispatchStatus]]:
    """
    Returns the current state of the particle distributions.
    """
    if gen_ids is None:
        gen_ids = list_generator_ids(localizer)
    return list(
        (gen_id, get_generation_status(gen_id, localizer)) for gen_id in gen_ids
    )


def delete_particle_distribution(
    gen_id: str,
    localizer: HostLocalizer,
    force: bool = False,
) -> list[str] | None:
    """
    Deletes the particle distribution file for a given generator ID.

    Returns a list of symlinks that are referencing the distribution file and blocking the deletion when not forced. Otherwise, returns None.
    """
    path = localizer.generator_path(gen_id)
    if not os.path.exists(path):
        return

    if not force:
        # delete only when nothing is referencing it
        links = find_symlinks(
            localizer.generator_path(gen_id, "distribution.ini"),
            localizer.data_path(),
            link_name="run.0000.001",
        )
        if len(links) > 0:
            return links
        # now its safe to remove

    rmtree(path)
    return


def write_particle_distribution(
    particles: Particles, localizer: HostLocalizer, comment: str | None = None
) -> str:
    """
    Writes the particle distribution to disk.
    """
    gen_id = get_uuid()
    dist_path = localizer.generator_path(gen_id, "distribution.ini")

    if os.path.exists(dist_path):
        raise RuntimeError("Generated ID already exists.")
    os.makedirs(os.path.dirname(dist_path), exist_ok=True)

    particles.write_to_csv(dist_path)

    meta = GeneratorMeta(comment=comment)
    meta_path = localizer.generator_path(gen_id, "meta.json")
    write_json(meta, path=meta_path)

    return gen_id


def get_generation_status(ge_id: str, localizer: HostLocalizer) -> DispatchStatus:
    """
    Returns status of the particle generation.
    """
    path = localizer.generator_path(ge_id, "generator.err")
    if os.path.isfile(path) and os.path.getsize(path) > 0:
        return DispatchStatus.FAILED
    path = localizer.generator_path(ge_id, "generator.out")
    if os.path.isfile(path):
        if "phase-space distribution saved to file" in read_txt(path):
            return DispatchStatus.FINISHED
    return DispatchStatus.UNFINISHED
