services:
  api:
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
    env_file:
      - .env
    environment:
      ASTRA_BINARY_PATH: /usr/local/bin
    volumes:
      - ${ASTRA_DATA_PATH:-data}:/app/data
    networks:
      - astra
    restart: unless-stopped

volumes:
  data:


networks:
  astra:
    driver: bridge
